// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	ConfigNameRequest
	ConfigValueReply
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigNameRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ConfigNameRequest) Reset()                    { *m = ConfigNameRequest{} }
func (m *ConfigNameRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigNameRequest) ProtoMessage()               {}
func (*ConfigNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConfigValueReply struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *ConfigValueReply) Reset()                    { *m = ConfigValueReply{} }
func (m *ConfigValueReply) String() string            { return proto.CompactTextString(m) }
func (*ConfigValueReply) ProtoMessage()               {}
func (*ConfigValueReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*ConfigNameRequest)(nil), "config.ConfigNameRequest")
	proto.RegisterType((*ConfigValueReply)(nil), "config.ConfigValueReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Config service

type ConfigClient interface {
	Env(ctx context.Context, in *ConfigNameRequest, opts ...grpc.CallOption) (*ConfigValueReply, error)
}

type configClient struct {
	cc *grpc.ClientConn
}

func NewConfigClient(cc *grpc.ClientConn) ConfigClient {
	return &configClient{cc}
}

func (c *configClient) Env(ctx context.Context, in *ConfigNameRequest, opts ...grpc.CallOption) (*ConfigValueReply, error) {
	out := new(ConfigValueReply)
	err := grpc.Invoke(ctx, "/config.Config/Env", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Config service

type ConfigServer interface {
	Env(context.Context, *ConfigNameRequest) (*ConfigValueReply, error)
}

func RegisterConfigServer(s *grpc.Server, srv ConfigServer) {
	s.RegisterService(&_Config_serviceDesc, srv)
}

func _Config_Env_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).Env(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Config/Env",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).Env(ctx, req.(*ConfigNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Config_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Env",
			Handler:    _Config_Env_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xd4, 0xb9, 0x04,
	0x9d, 0xc1, 0x2c, 0xbf, 0xc4, 0xdc, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21,
	0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49,
	0x83, 0x4b, 0x00, 0xa2, 0x30, 0x2c, 0x31, 0xa7, 0x34, 0x35, 0x28, 0xb5, 0x20, 0xa7, 0x52, 0x48,
	0x84, 0x8b, 0xb5, 0x0c, 0xc4, 0x83, 0x2a, 0x84, 0x70, 0x8c, 0xdc, 0xb8, 0xd8, 0x20, 0x2a, 0x85,
	0x6c, 0xb8, 0x98, 0x5d, 0xf3, 0xca, 0x84, 0x24, 0xf5, 0xa0, 0x56, 0x63, 0xd8, 0x24, 0x25, 0x81,
	0x2a, 0x85, 0x30, 0x5b, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x52, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0x7d, 0xaf, 0x79, 0xb9, 0x00, 0x00, 0x00,
}
